### ISSUE TITLE
Make recent files start from the last file (not the current one)

### ISSUE THREAD

**Issue by andybergon** [wahyd4/vscode-plugin-recent-files#10]
I think a great way to give a new life to this plugin can be to make it behave exactly like IntelliJ.

If you search for recent files you get the list but the cursor starts from the second element as you don't want to go to your current file but to your last file as a default.

I am not very experienced with vscode extensions but I can fork and give it a try.

Now:
![image](https://user-images.githubusercontent.com/5220825/38462867-64afad5c-3ae5-11e8-9f6c-37494d22471e.png)

Expected:
![image](https://user-images.githubusercontent.com/5220825/38462870-6f5640fe-3ae5-11e8-8775-e7f99bd54eaf.png)

**Comment by wahyd4** [comment]
I think the screenshot you took is not the functionality of my plugin, rather than the system `workbench.action.quickOpen` plugin.

To enable my plugin you need to modify the `keybindings.json`, and the UI should like this when my plugin enabled:

<img width="636" alt="screen shot 2018-04-08 at 13 38 43" src="https://user-images.githubusercontent.com/836576/38462985-a8cd84e4-3b32-11e8-9bc1-9c26fd4580b2.png">

**Comment by andybergon** [comment]
Yes, I know the screenshots were from the system quick open. 

I was just suggesting a way to get your great plugin useful again (as it is superseded from built in vscode right now) but I found that also [what I was suggesting is in the built in vscode](https://github.com/Microsoft/vscode/issues/47413) as `quickOpenRecentEditor`.

Thanks :)

**Comment by wahyd4** [comment]
Thank you for your suggestion. I'm kind of thinking my plugin is not so useful anymore, so maybe spend some time on other things rather than this plugin. If you are keen to do some change please feel free to make a pull request. Cheers!

By the way, the `quickOpenPreviousEditor` is really cool, thanks.
